const {test,expect} = require ('@playwright/test');
test('Client App Automation Practice',async ({browser})=>
    {
        const email = "umang1112@gmail.com";
        const context = await browser.newContext();
        const page = await context.newPage();
        const username = page.getByPlaceholder("email@example.com");
        const password = page.getByPlaceholder("enter your passsword");
        const login = page.getByRole("button",{name: 'Login'});
        const cardtitles = page.locator(".card-body b");
        const products = page.locator(".card-body"); /* Iteration of all products in a page */
        const cart = page.getByRole("listitem").getByRole("button",{name:"Cart"});
        await page.goto("https://rahulshettyacademy.com/client/");
        console.log(await page.title());
        await username.fill(email);
        await password.fill("Umang@1104812");
        await expect(login).toContainText("Login");
        await login.click();
        await page.waitForLoadState('networkidle');
        await cardtitles.first().waitFor();
        console.log(await cardtitles.first().textContent());
        await expect(cardtitles.nth(0)).toContainText("ADIDAS ORIGINAL");
        const alltitles = await cardtitles.allTextContents();
        console.log(alltitles);
        await page.locator(".card-body").filter({hasText:'ADIDAS ORIGINAL'}).getByRole("button",{name:" Add To Cart"}).click(); //chaining of steps
        await cart.click();
        await page.waitForLoadState('networkidle');
        await page.locator("li").filter({hasText: 'ADIDAS ORIGINAL'}).waitFor();
        const item_visible = await page.getByText("ADIDAS ORIGINAL").isVisible();
        await expect(item_visible).toBeTruthy();
        const item_number = await page.locator("p.itemNumber").textContent();
        const primary_button = page.getByRole("button",{name:"Checkout"});
        await primary_button.click();
        await page.waitForLoadState('networkidle');
        const next_page = page.locator(".form__cc");
        await next_page.waitFor();
        await page.locator("div.field:has(div.title:has-text('CVV Code')) input").fill("000");
        await page.locator("div.field:has(div.title:has-text('Name')) input").fill("James Bond");
        await page.locator("div.field:has(div.title:has-text('Apply Coupon')) input").fill("rahulshettyacademy");
        const apply_coupon = await page.getByRole("button",{name:"Apply Coupon"});
        await apply_coupon.click();
        const success_message = await page.locator("p.mt-1.ng-star-inserted");
        await expect(success_message).toContainText("* Coupon Applied");
        await page.getByPlaceholder("Select Country").pressSequentially("Ind");
        const dropdown = page.locator(".ta-results.list-group.ng-star-inserted");
        await dropdown.waitFor();
        await page.getByRole("button",{name:"India"}).nth(1).click();
        await expect(page.locator(".user__name [type='text']").first()).toHaveText(email);
        await page.getByText("PLACE ORDER").click();
        await page.waitForLoadState('networkidle');
        await expect(page.getByText(" Thankyou for the order. ")).toBeVisible();
        const orderid = await page.locator("td.em-spacer-1 label.ng-star-inserted").textContent();
        console.log(orderid);
        const cleaned_orderid = orderid.replace(/\|/g, "");
        console.log(cleaned_orderid);
        await page.getByRole("button",{name:"ORDERS"}).first().click();
        await page.waitForLoadState('networkidle');
        await page.locator("tbody").waitFor();
        await page.getByRole("button",{name:"View"}).nth(0).click();
        await page.waitForLoadState('networkidle');
        const result_order_id_locator = page.locator(`text=${cleaned_orderid.trim()}`);
        await result_order_id_locator.waitFor({ state: 'visible', timeout: 5000 });
        const result_order_id = (await result_order_id_locator.first().textContent()).trim();
        await expect(orderid.includes(result_order_id)).toBeTruthy();
        await page.getByText(email);
        await page.getByText("India");
        await expect(page.getByText("ADIDAS ORIGINAL")).toBeTruthy();
    }
);